DROP TABLE TB_COMENT_RELATO;
DROP TABLE TB_RELATO;
DROP TABLE TB_COMENT_CURSO;
DROP TABLE TB_CURSO;
DROP TABLE TB_COMENT_ARTIGO;
DROP TABLE TB_ARTIGO;
DROP TABLE TB_USU_PROF;
DROP TABLE TB_USU_ADMIN;
DROP TABLE TB_USUARIO;

CREATE TABLE TB_USUARIO (
ID_USU INTEGER PRIMARY KEY,
NM_USU VARCHAR2(30) NOT NULL,
SBNM_USU VARCHAR2(120),
DT_NASC DATE NOT NULL,
DT_CADASTRO DATE,
EMAIL VARCHAR2(100) NOT NULL,
PW_USU VARCHAR2(40) NOT NULL
);

CREATE TABLE TB_USU_PROF (
ID_PROF INTEGER PRIMARY KEY,
CRM_COREN VARCHAR2(15) NOT NULL,
DT_FORM DATE  NOT NULL,
ESPEC_PROF VARCHAR2(80), 
UF_ATUA VARCHAR2(2),
CIDADE_ATUA VARCHAR2(40),
ID_USU REFERENCES TB_USUARIO(ID_USU)
);

CREATE TABLE TB_USU_ADMIN (
ID_ADMIN INTEGER PRIMARY KEY,
ID_USU REFERENCES TB_USUARIO(ID_USU)
);


CREATE TABLE TB_CURSO (
ID_CURSO INTEGER PRIMARY KEY,
DESC_CURSO VARCHAR2(500),
LINK_CURSO VARCHAR2(200),
DT_PUBLI_CURSO DATE,
ID_USU REFERENCES TB_USUARIO(ID_USU)
);

CREATE TABLE TB_COMENT_CURSO (
ID_COMENT_CURSO INTEGER PRIMARY KEY,
COMENTARIO_CURSO VARCHAR2(1000),
DT_COMENT_CURSO DATE,
ID_CURSO REFERENCES TB_CURSO(ID_CURSO),
ID_USU REFERENCES TB_USUARIO(ID_USU)
);


CREATE TABLE TB_ARTIGO (
ID_ARTIGO INTEGER PRIMARY KEY,
DESC_ARTIGO VARCHAR2(1000),
LINK_ARTIGO VARCHAR2(200),
DT_ARTIGO DATE,
ID_USU REFERENCES TB_USUARIO(ID_USU)
);

CREATE TABLE TB_COMENT_ARTIGO (
ID_COMENT_ARTIGO INTEGER PRIMARY KEY,
COMENTARIO_ARTIGO VARCHAR2(1000),
DT_COMENT_ARTIGO DATE,
ID_ARTIGO REFERENCES TB_ARTIGO(ID_ARTIGO),
ID_USU REFERENCES TB_USUARIO(ID_USU)
);


CREATE TABLE TB_RELATO (
ID_RELATO INTEGER PRIMARY KEY,
TEMA_RELATO VARCHAR2(100),
TITULO_RELATO VARCHAR2(100),
DESC_RELATO VARCHAR2(1000),
DT_RELATO DATE,
ID_USU REFERENCES TB_USUARIO(ID_USU)
);

CREATE TABLE TB_COMENT_RELATO (
ID_COMENT_RELATO INTEGER PRIMARY KEY,
COMENTARIO_RELATO VARCHAR2(1000),
DT_COMENT_RELATO DATE,
ID_RELATO REFERENCES TB_RELATO(ID_RELATO),
ID_USU REFERENCES TB_USUARIO(ID_USU)
);